# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70bee80c7569e738d208668c76dcf7cacdf9c0f971f0d4de0e3aa73e4b87c9b575e21f3f9249ebd0bd2c16c478910de8f71b0f640594abd8936147c04be1e3db
  omniauth_provider_key: ENV["OMNIAUTH_PROVIDER_KEY"]
  omniauth_provider_secret: ENV["OMNIAUTH_PROVIDER_SECRET"]
test:
  secret_key_base: 4934ba7c23be880ccf94de7770608ce35caaebe0ed41d391640502f30f8ad1cbc7a3139a1a8de5bf67c78a17e58e714b29f4c89b4d2ee4d244cfd2f246a722b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  omniauth_provider_key: ENV["OMNIAUTH_PROVIDER_KEY"]
  omniauth_provider_secret: ENV["OMNIAUTH_PROVIDER_SECRET"]
